version: "3"
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - client

  client:
    build: ./client
    ports:
      - "8080:80"
    volumes:
      - ./client:/usr/share/nginx/html
